version: '3.6'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: penTestDB
    ports:
      - 5432:5432
    restart: always
    container_name: docker_postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  func:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 7071:80
    container_name: az_func